# Generated by Django 5.0.4 on 2024-05-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="classification",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
