# Generated by Django 5.0.4 on 2024-05-18 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userAPI", "0002_uploadedimage_classification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="classification",
        ),
    ]
