# Generated by Django 5.0.4 on 2024-05-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appSettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="value",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
